### ISSUE TITLE
Azure Active Directory (Azure AD) SSO authentication for employees within Galvanize

### ISSUE THREAD

**Issue by yehee** [2019W1-CPSC319/optimize-prime#30]
Note:
* Is this done? I think at one point I was able to log in using my SSO for SAP, which convinces me that this is in place.

**Comment by dustxd** [comment]
What is SSO?

**Comment by yehee** [comment]
Just saw this! Reference to this: https://en.wikipedia.org/wiki/Single_sign-on. To my understanding, using email address like `example@sap.com` uses a certificate when logging in to Outlook. Correct me if I'm wrong!

**Comment by martinjoha** [comment]
Is this okay to close?
